### ISSUE TITLE
[Milestone 3] - Add fields to enter in the profile page

### ISSUE THREAD

**Issue by shehabadel** [shehabadel/Wagba#6]
More like to complete profile setup. A user needs to add his name, university, year...etc. inside the profile page.

Then update it in the Room's Database.

**Comment by shehabadel** [comment]
- [ ] Update the `User` model
- [ ] Update the `userDao`
- [ ] Update the `UserRepo`
- [ ] Update the logout functionality to not remove users
- [ ] update the login functionality to insert `User` by his email
- [ ] Update the profile to get the `User` by his `email` from the `FirebaseAuth`

**Comment by shehabadel** [comment]
- [ ] Add `TextView` and `EditText` to add and update the `User`'s name, year, and department
- [ ] Upon pressing save, we need to update the data in Room's Database.
