### ISSUE TITLE
[Milestone 3] - Implement order functionality

### ISSUE THREAD

**Issue by shehabadel** [shehabadel/Wagba#9]
- [x] Pass the `CartModel` to the `PaymentActivity`
- [x] Create a new Order and clear the `Cart` upon pressing `Place Order`
- [x] Create Order Model, ViewModel, Repo to track the order in the `Tracking` fragment.

**Comment by shehabadel** [comment]
- [ ] Create a method to fetch previous orders from previous orders node to populate them inside the previous orders recycler view
- [ ] Create a method to create a new order to be pushed in the order node
- [ ]  Add an order to `order` node and previous orders node upon pressing 'place order' with the state being `confirmed` initially
- [ ] create a method to update the order state
- [ ] create a method to delete the order upon receiving it which is going to be used inside the dashboard
- [ ] create a method to create an order
- [ ] create a method to fetch the current order
